name: podstream
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1
  go_router: ^15.1.1
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/logo.png"
  min_sdk_android: 24 
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logos/logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/logos/

